#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
mpd &
polybar &
dunst &
~./fehbg &
discord &

bspc monitor -d eins zwei drei vier fünf

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Thunar state=floating follow=on
