#! /bin/sh

sxhkd &
picom &
nitrogen --restore &
dunst &
polybar &

# bspwm settings
bspc monitor -d eins zwei drei vier fünf &
bspc config window_gap 12
bspc config border_width 2
bspc config normal_border_color "#313244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
