#! /bin/sh

sxhkd &
picom -b --experimental-backends --backend glx
~/.fehbg &
dunst &
polybar &
mpd &

# bspwm settings
bspc monitor -d eins zwei drei vier fünf &
bspc config window_gap 0
bspc config border_width 2
bspc config normal_border_color "#6c7086"
bspc config focused_border_color "#cdd6f4"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
