window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: .90

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Jetbrains Mono Nerd Font
    style:  Regular
  bold:
    family: Jetbrains Mono Nerd Font
    style:  Bold
  italic:
    family: Jetbrains Mono Nerd Font
    style:  Italic
  bold_italic:
    family: Jetbrains Mono Nerd Font
    style: Bold Italic
  size: 14
draw_bold_text_with_bright_colors: true

import:
  - ~/.config/alacritty/catppuccin-mocha.yml

selection:
  save_to_clipboard: false
