import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[font]
size = 12

[font.bold]
family = "Jetbrains Mono Nerd Font Propo"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Jetbrains Mono Nerd Font SemBd"
style = "Italic"

[font.normal]
family = "Jetbrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
opacity = 0.9

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 15
y = 15
